//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int EmpleyeeId { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public string PhotoFileName { get; set; }
        public int DepartmentId { get; set; }
    }
}
